[package]
name = "rollcage-extractor"
version = "0.1.0"
authors = []
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rollcage-file-parser = { path = "Rollcage-File-Parser" }
clap = "~2.33.0"